// Given.swift
// Sensory data with vector embedding

import Foundation
import Database

/// A unit of sensory input selected by MemoryEncoder as worth remembering.
///
/// Not the raw input itself, but a filtered material with embedding.
@Persistable
public struct Given {

    #Directory<Given>("memory", "givens")

    #Index(ScalarIndexKind<Given>(fields: [\.timestamp]))
    #Index(ScalarIndexKind<Given>(fields: [\.source]))
    #Index(VectorIndexKind<Given>(embedding: \.embedding, dimensions: 256, metric: .cosine))

    /// Time-sortable unique identifier (ULID).
    public var id: String = ULID().ulidString

    /// Input modality: "text", "image", "audio".
    public var modality: String

    /// Inline text content or blob store reference.
    public var payloadRef: String

    /// Vector embedding generated by MemoryEncoding implementation.
    public var embedding: [Float]

    /// Timestamp when this given was created.
    public var timestamp: Date

    /// Identifier of the input source.
    public var source: String
}

extension Given {

    /// Embedding vector dimensionality used by the VectorIndex.
    public static let embeddingDimensions: Int = 256

    /// IRI for use as Statement subject/object.
    public var iri: String { "memory:given/\(id)" }
}
