// Given.swift
// Sensory data with vector embedding

import DatabaseKit

/// A unit of sensory input selected by MemoryEncoder as worth remembering.
///
/// Not the raw input itself, but a filtered material with embedding.
@Persistable
public struct Given {

    #Directory<Given>("memory", "givens")

    #Index(.ordered(name: "Given_timestamp", keys: [.ascending(\Given.timestamp)]))
    #Index(.ordered(name: "Given_source", keys: [.ascending(\Given.source)]))
    #Index(
        .vector(
            name: "Given_vector_embedding",
            embedding: \Given.embedding,
            dimensions: 768,
            metric: .cosine
        )
    )

    /// Time-sortable unique identifier (ULID).
    public var id: String

    /// Input modality: "text", "image", "audio".
    public var modality: String

    /// Inline text content or blob store reference.
    public var payloadRef: String

    /// Vector embedding generated by MemoryEncoding implementation.
    public var embedding: Vector

    /// Timestamp when this given was created.
    public var timestamp: Timestamp

    /// Identifier of the input source.
    public var source: String
}

extension Given {

    /// Embedding vector dimensionality used by the VectorIndex.
    public static let embeddingDimensions: Int = 768

    /// IRI for use as Statement subject/object.
    public var iri: String { "memory:given/\(id)" }
}

extension Given: SecurityPolicy {
    public static func permitsRead(
        of resource: borrowing Given,
        in context: borrowing AuthorizationContext
    ) -> Bool { true }

    public static func permitsQuery(
        _ query: borrowing SecurityQuery,
        in context: borrowing AuthorizationContext
    ) -> Bool { true }

    public static func permitsCreate(
        _ newResource: borrowing Given,
        in context: borrowing AuthorizationContext
    ) -> Bool { true }

    public static func permitsUpdate(
        from resource: borrowing Given,
        to newResource: borrowing Given,
        in context: borrowing AuthorizationContext
    ) -> Bool { true }

    public static func permitsDelete(
        _ resource: borrowing Given,
        in context: borrowing AuthorizationContext
    ) -> Bool { true }
}
